name: whatsapp_stickers_example_dynamic
description: Demonstrates how to use the whatsapp_stickers plugin with dynamic content.
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  archive: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_whatsapp_stickers:
    path: ../

flutter:
  uses-material-design: true

  assets:
    - sticker_packs/cats.zip
    - sticker_packs/dragon.zip
